# -*- coding: utf-8 -*-
"""Untitled161.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rHuEmnVNGo6bQVfDHWMNOy-nCZKiGPq
"""

import pandas as pd

df = pd.read_csv("/content/credit_card.csv")

print(df.columns)
print(df.head())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

df.columns = df.columns.str.strip()
print(df.columns)

cust_ids = df["CUST_ID"]

X = df.drop("TENURE", axis=1)

print("Original df columns:")
print(df.columns)

print("X columns after dropping TENURE:")
print(X.columns)

X = X.fillna(X.mean(numeric_only=True))
print(X.columns)

if "CUST_ID" in X.columns:
    X["CUST_ID"] = pd.factorize(X["CUST_ID"])[0]
    print(X["CUST_ID"].head(10))

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

model = IsolationForest(
    n_estimators=100,
    contamination=0.05,
    random_state=42
)

pred = model.fit_predict(X_scaled)
print(pred)

df["Fraud_Flag"] = pred
df["Fraud_Flag"] = df["Fraud_Flag"].map({1: 0, -1: 1})
print(df.head())

df["CUST_ID"] = cust_ids
print(df.head())

print("\nFraud Detection Count:")
print(df["Fraud_Flag"].value_counts())

print("\n0 = Normal Customers")
print("1 = Suspicious Customers")

fraud = df[df["Fraud_Flag"] == 1]

print("\nTop 10 Suspicious Customers:")
print(fraud.head(10))

plt.figure(figsize=(7,5))
sns.countplot(x="Fraud_Flag", data=df, palette="Set2")

plt.title("Fraud Detection Result", fontsize=14, fontweight="bold")
plt.xlabel("Fraud Flag")
plt.ylabel("Count")
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(
    df["CASH_ADVANCE"],
    df["PAYMENTS"],
    c=df["Fraud_Flag"],
    cmap="coolwarm"
)
plt.xlabel("Cash Advance")
plt.ylabel("Payments")
plt.title("Suspicious Customer Detection")
plt.show()

from google.colab import files
files.download('fraud_detection_output.csv')